spring:
  datasource:
    master:
      url: jdbc:mysql://localhost:3306/master_db
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: master_user
      password: master_password
    slave:
      url: jdbc:mysql://localhost:3306/slave_db
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: slave_user
      password: slave_password
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
  h2:
    console:
      enabled: true
  cache:
    type: redis
  data:
    redis:
      host: localhost
      port: 6379

file:
  storage:
    location: D:\TEST

logging:
  level:
    org.springframework.data.redis: DEBUG
